
export const ADD_DOWNLOAD = 'ADD_DOWNLOAD'
export const DELETE_DOWNLOAD = 'DELETE_DOWNLOAD'
export const UPDATE_DOWNLOAD = 'UPDATE_DOWNLOAD'
export const UPDATE_DOWNLOAD_PROGRESS = 'UPDATE_DOWNLOAD_PROGRESS'
export const UPDATE_DOWNLOADLIST = 'UPDATE_DOWNLOADLIST'
