// 登录
export const TOGGLE_LOGIN_VIEW_VISIBLE = 'TOGGLE_LOGIN_VIEW_VISIBLE'
export const SET_ACCOUNT_INFO = 'SET_ACCOUNT_INFO'


// 注册
export const TOGGLE_REGISTER_VIEW_VISIBLE = 'TOGGLE_REGISTER_VIEW_VISIBLE'

// demand
// export const TOGGLE_REGISTER_VIEW_VISIBLE = 'TOGGLE_REGISTER_VIEW_VISIBLE'
